export const seedInhumados = [
  {
    id: 1,
    apellido: 'Abdelnur',
    nombre: 'Jose Antonio',
    fnac: '25 de Febrero de 1943',
    ffal: '9 de Mayo de 2000',
    valle: 'Sauces',
    sector: '-',
    manzana: 10,
    parcela: 112,
    simbolo: 1,
    ncliente: 93,
  },
  {
    id: 2,
    apellido: 'Aboy',
    nombre: 'Maria Delia',
    fnac: '6 de Agosto de 1910',
    ffal: '19 de Enero de 2004',
    valle: 'Nogales',
    sector: '-',
    manzana: 7,
    parcela: 42,
    simbolo: 1,
    ncliente: 758,
  },
  {
    id: 3,
    apellido: 'Accattoli',
    nombre: 'Magdalena Eulalia',
    fnac: '22 de Julio de 1909',
    ffal: '31 de Mayo de 1992',
    valle: 'Magnolias',
    sector: '-',
    manzana: 4,
    parcela: 81,
    simbolo: 1,
    ncliente: 3071,
  },
  {
    id: 4,
    apellido: 'Acevedo',
    nombre: 'Aida Rosa',
    fnac: '8 de Agosto de 1916',
    ffal: '21 de Julio de 2000',
    valle: 'Robles',
    sector: '-',
    manzana: 8,
    parcela: 232,
    simbolo: 1,
    ncliente: 1809,
  },
  {
    id: 5,
    apellido: 'Acosta',
    nombre: 'Marcela Beatriz',
    fnac: '16 de Agosto de 1965',
    ffal: '6 de Marzo de 2003',
    valle: 'Cipreses',
    sector: 'C',
    manzana: 2,
    parcela: 68,
    simbolo: 1,
    ncliente: 3242,
  },
  {
    id: 6,
    apellido: 'Acosta',
    nombre: 'Oscar Omar (Milo)',
    fnac: '10 de Septiembre de 1929',
    ffal: '6 de Marzo de 2003',
    valle: 'Cipreses',
    sector: '-',
    manzana: 2,
    parcela: 68,
    simbolo: 1,
    ncliente: 3242,
  },
  {
    id: 7,
    apellido: 'Acosta',
    nombre: 'Maria del Carmen',
    fnac: '31 de Diciembre de 1913',
    ffal: '14 de Agosto de 1990',
    valle: 'Magnolias',
    sector: '-',
    manzana: 9,
    parcela: 105,
    simbolo: 1,
    ncliente: 993,
  },
  {
    id: 8,
    apellido: 'Acosta',
    nombre: 'Ramón',
    fnac: '7 de Septiembre de 1921',
    ffal: '18 de Noviembre de 1988',
    valle: 'Robles',
    sector: '-',
    manzana: 7,
    parcela: 158,
    simbolo: 1,
    ncliente: 106,
  },
  {
    id: 9,
    apellido: 'Acosta',
    nombre: 'Dionisio',
    fnac: '9 de Agosto de 1936',
    ffal: '4 de Mayo de 2001',
    valle: 'Robles',
    sector: '-',
    manzana: 8,
    parcela: 214,
    simbolo: 1,
    ncliente: 3129,
  },
  {
    id: 10,
    apellido: 'Acosta Vda. De Gomez',
    nombre: 'Olimpia',
    fnac: '10 de Mayo de 1926',
    ffal: '26 de Septiembre de 1998',
    valle: 'Robles',
    sector: '-',
    manzana: 8,
    parcela: 156,
    simbolo: 1,
    ncliente: 376,
  },
  {
    id: 11,
    apellido: 'Acuña',
    nombre: 'Miguel Horacio',
    fnac: '4 de Julio de 1929',
    ffal: '20 de Junio de 1998',
    valle: 'Robles',
    sector: '-',
    manzana: 7,
    parcela: 207,
    simbolo: 1,
    ncliente: 1588,
  },
  {
    id: 13,
    apellido: 'Acuña',
    nombre: 'Camilo',
    fnac: '18 de Julio de 1911',
    ffal: '13 de Abril de 1964',
    valle: 'Robles',
    sector: '-',
    manzana: 7,
    parcela: 193,
    simbolo: 1,
    ncliente: 1764,
  },
  {
    id: 14,
    apellido: 'Acuña',
    nombre: 'Pedro Enrique',
    fnac: '28 de Junio de 1928',
    ffal: '19 de Mayo de 2000',
    valle: 'Robles',
    sector: '-',
    manzana: 10,
    parcela: 152,
    simbolo: 1,
    ncliente: 1805,
  },
  {
    id: 15,
    apellido: 'Adin',
    nombre: 'Pantaleon',
    fnac: '18 de Julio de 1918',
    ffal: '9 de Junio de 1999',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 4,
    parcela: 84,
    simbolo: 1,
    ncliente: 1261,
  },
  {
    id: 16,
    apellido: 'Agudo',
    nombre: 'Ines',
    fnac: '-',
    ffal: '2 de Octubre de 2000',
    valle: 'Robles',
    sector: '-',
    manzana: 12,
    parcela: 167,
    simbolo: 1,
    ncliente: 2025,
  },
  {
    id: 18,
    apellido: 'Agueda',
    nombre: 'Jose Elidor',
    fnac: '-',
    ffal: '21 de Octubre de 2000',
    valle: 'Robles',
    sector: '-',
    manzana: 6,
    parcela: 76,
    simbolo: 1,
    ncliente: 547,
  },
  {
    id: 19,
    apellido: 'Aguilera',
    nombre: 'Juan Jose',
    fnac: '21 de Mayo de 1953',
    ffal: '25 de Enero de 2004',
    valle: 'Robles',
    sector: '-',
    manzana: 12,
    parcela: 77,
    simbolo: 1,
    ncliente: 3365,
  },
  {
    id: 20,
    apellido: 'Aguirre',
    nombre: 'Zulema',
    fnac: '23 de Junio de 1935',
    ffal: '2 de Junio de 2000',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 10,
    parcela: 30,
    simbolo: 1,
    ncliente: 1709,
  },
  {
    id: 21,
    apellido: 'Aguirre',
    nombre: 'Maria Luisa',
    fnac: '-',
    ffal: '22 de Diciembre de 2000',
    valle: 'Nogales',
    sector: '-',
    manzana: 10,
    parcela: 68,
    simbolo: 1,
    ncliente: 848,
  },
  {
    id: 22,
    apellido: 'Aguirrez',
    nombre: 'Teresita Ana',
    fnac: '22 de Septiembre de 1934',
    ffal: '12 de Enero de 2000',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 4,
    parcela: 89,
    simbolo: 1,
    ncliente: 1582,
  },
  {
    id: 23,
    apellido: 'Ahumada',
    nombre: 'Manuel Diogenes',
    fnac: '6 de Marzo de 1925',
    ffal: '28 de Mayo de 1999',
    valle: 'Magnolias',
    sector: '-',
    manzana: 10,
    parcela: 15,
    simbolo: 1,
    ncliente: 854,
  },
  {
    id: 24,
    apellido: 'Albiano',
    nombre: 'Francisco Domingo',
    fnac: '17 de Mayo de 1904',
    ffal: '8 de Diciembre de 1987',
    valle: 'Magnolias',
    sector: '-',
    manzana: 9,
    parcela: 36,
    simbolo: 1,
    ncliente: 1346,
  },
  {
    id: 25,
    apellido: 'Albiati',
    nombre: 'Enrique Juan',
    fnac: '10 de Marzo de 1920',
    ffal: '22 de Marzo de 1999',
    valle: 'Nogales',
    sector: '-',
    manzana: 7,
    parcela: 116,
    simbolo: 1,
    ncliente: 926,
  },
  {
    id: 26,
    apellido: 'Albino Garzon',
    nombre: 'Freddy Alberto',
    fnac: '15 de Diciembre de 1984',
    ffal: '29 de Junio de 2001',
    valle: 'Robles',
    sector: '-',
    manzana: 7,
    parcela: 152,
    simbolo: 1,
    ncliente: 3143,
  },
  {
    id: 27,
    apellido: 'Albornoz',
    nombre: 'Andres Ramon',
    fnac: '10 de Noviembre de 1926',
    ffal: '20 de Septiembre de 1999',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 2,
    parcela: 76,
    simbolo: 1,
    ncliente: 726,
  },
  {
    id: 28,
    apellido: 'Aldana Maciel',
    nombre: 'Lorenza Ignacia',
    fnac: '5 de Septiembre de 1910',
    ffal: '11 de Octubre de 1998',
    valle: 'Robles',
    sector: '-',
    manzana: 7,
    parcela: 219,
    simbolo: 1,
    ncliente: 1548,
  },
  {
    id: 29,
    apellido: 'Alegre',
    nombre: 'Amada Eleuteria',
    fnac: '4 de Marzo de 1922',
    ffal: '16 de Septiembre de 1999',
    valle: 'Magnolias',
    sector: '-',
    manzana: 12,
    parcela: 23,
    simbolo: 1,
    ncliente: 1701,
  },
  {
    id: 30,
    apellido: 'Alesandro',
    nombre: 'Angela',
    fnac: '16 de Octubre de 1917',
    ffal: '9 de Octubre de 2004',
    valle: 'Robles',
    sector: '-',
    manzana: 9,
    parcela: 149,
    simbolo: 1,
    ncliente: 130,
  },
  {
    id: 31,
    apellido: 'Alfenoni',
    nombre: 'Dante Felix',
    fnac: '12 de Julio de 1921',
    ffal: '17 de Mayo de 1977',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 4,
    parcela: 80,
    simbolo: 1,
    ncliente: 1153,
  },
  {
    id: 32,
    apellido: 'Almiron',
    nombre: 'Maria Armenia (Nina)',
    fnac: '6 de Octubre de 1930',
    ffal: '24 de Diciembre de 2000',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 8,
    parcela: 87,
    simbolo: 1,
    ncliente: 3220,
  },
  {
    id: 33,
    apellido: 'Alomo',
    nombre: 'Justa Pastora',
    fnac: '27 de Julio de 1944',
    ffal: '18 de Abril de 2002',
    valle: 'Robles',
    sector: '-',
    manzana: 1,
    parcela: 55,
    simbolo: 1,
    ncliente: 3223,
  },
  {
    id: 34,
    apellido: 'Alonso',
    nombre: 'Atilano',
    fnac: '16 de Junio de 1964',
    ffal: '24 de Enero de 2004',
    valle: 'Robles',
    sector: '-',
    manzana: 13,
    parcela: 82,
    simbolo: 1,
    ncliente: 3417,
  },
  {
    id: 35,
    apellido: 'Alonso',
    nombre: 'Raul Federico',
    fnac: '19 de Diciembre de 1924',
    ffal: '16 de Enero de 1987',
    valle: 'Sauces',
    sector: '-',
    manzana: 15,
    parcela: 52,
    simbolo: 1,
    ncliente: 1471,
  },
  {
    id: 37,
    apellido: 'Alpuin',
    nombre: 'Maria Delfina',
    fnac: '26 de Abril de 1915',
    ffal: '17 de Noviembre de 2004',
    valle: 'Nogales',
    sector: '-',
    manzana: 7,
    parcela: 102,
    simbolo: 1,
    ncliente: 163,
  },
  {
    id: 38,
    apellido: 'Alvarez',
    nombre: 'Agustina Rosa',
    fnac: '28 de Agosto de 1909',
    ffal: '23 de Abril de 1999',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 4,
    parcela: 72,
    simbolo: 1,
    ncliente: 943,
  },
  {
    id: 39,
    apellido: 'Alvarez',
    nombre: 'Petronila Pascuala (Tita)',
    fnac: '17 de Mayo de 1913',
    ffal: '14 de Julio de 2001',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 8,
    parcela: 73,
    simbolo: 1,
    ncliente: 3145,
  },
  {
    id: 40,
    apellido: 'Alvarez Latorre',
    nombre: 'Maria',
    fnac: '22 de Julio de 1905',
    ffal: '22 de Febrero de 2005',
    valle: 'Sauces',
    sector: '-',
    manzana: 15,
    parcela: 52,
    simbolo: 1,
    ncliente: 1471,
  },
  {
    id: 41,
    apellido: 'Amado',
    nombre: 'Lorenza',
    fnac: '-',
    ffal: '23 de Mayo de 2001',
    valle: 'Robles',
    sector: '-',
    manzana: 12,
    parcela: 146,
    simbolo: 1,
    ncliente: 845,
  },
  {
    id: 42,
    apellido: 'Amaya',
    nombre: 'Casilda del Carmen',
    fnac: '16 de Julio de 1915',
    ffal: '1 de Junio de 1989',
    valle: 'Cipreses',
    sector: 'B',
    manzana: 12,
    parcela: 87,
    simbolo: 1,
    ncliente: 3168,
  },
  {
    id: 43,
    apellido: 'Ambrosini',
    nombre: 'Atilio',
    fnac: '29 de Mayo de 1918',
    ffal: '5 de Enero de 2000',
    valle: 'Magnolias',
    sector: '-',
    manzana: 9,
    parcela: 78,
    simbolo: 1,
    ncliente: 1612,
  },
  {
    id: 44,
    apellido: 'Amenabal',
    nombre: 'Santiago',
    fnac: '25 de Mayo de 1923',
    ffal: '19 de Agosto de 1998',
    valle: 'Robles',
    sector: '-',
    manzana: 8,
    parcela: 165,
    simbolo: 1,
    ncliente: 1279,
  },
  {
    id: 45,
    apellido: 'Amoresano',
    nombre: 'Carla Grisel',
    fnac: '20 de Diciembre de 1980',
    ffal: '3 de Abril de 1999',
    valle: 'Robles',
    sector: '-',
    manzana: 9,
    parcela: 79,
    simbolo: 1,
    ncliente: 870,
  },
  {
    id: 46,
    apellido: 'Angeleri',
    nombre: 'Zulema Rosa',
    fnac: '4 de Febrero de 1921',
    ffal: '26 de Marzo de 2002',
    valle: 'Sauces',
    sector: '-',
    manzana: 6,
    parcela: 125,
    simbolo: 1,
    ncliente: 92,
  },
  {
    id: 47,
    apellido: 'Angeletti de Borra',
    nombre: 'Josefa Elena',
    fnac: '15 de Noviembre de 1924',
    ffal: '26 de Abril de 2005',
    valle: 'Robles',
    sector: '-',
    manzana: 10,
    parcela: 130,
    simbolo: 1,
    ncliente: 1492,
  },
  {
    id: 48,
    apellido: 'Angelini',
    nombre: 'Raul Felipe',
    fnac: '18 de Julio de 1913',
    ffal: '14 de Julio de 1999',
    valle: 'Magnolias',
    sector: '-',
    manzana: 10,
    parcela: 68,
    simbolo: 1,
    ncliente: 1305,
  },
  {
    id: 49,
    apellido: 'Angeloni',
    nombre: 'Miguel Angel',
    fnac: '-',
    ffal: '22 de Noviembre de 1998',
    valle: 'Nogales',
    sector: '-',
    manzana: 7,
    parcela: 104,
    simbolo: 1,
    ncliente: 494,
  },
  {
    id: 50,
    apellido: 'Aquin',
    nombre: 'Alberto Omar',
    fnac: '11 de Septiembre de 1940',
    ffal: '2 de Septiembre de 2004',
    valle: 'Robles',
    sector: '-',
    manzana: 12,
    parcela: 191,
    simbolo: 1,
    ncliente: 3391,
  },
];
